model_list:
  - model_name: bedrock-claude-v3-sonnet-user1
    litellm_params:
      model: bedrock/anthropic.claude-3-sonnet-20240229-v1:0
      aws_region_name: "us-west-2"
      aws_access_key_id: ""
      aws_secret_access_key: ""
      rpm: 3
  - model_name: bedrock-claude-v3-haiku-user2
    litellm_params:
      model: bedrock/anthropic.claude-3-haiku-20240307-v1:0
      aws_region_name: "us-west-2"
      aws_access_key_id: ""
      aws_secret_access_key: ""
      rpm: 5
router_settings:
  routing_strategy: simple-shuffle
  redis_host: os.environ/REDIS_HOST
  redis_password: os.environ/REDIS_PASSWORD
  redis_port: os.environ/REDIS_PORT
# general_settings: 
#   master_key: sk-1234